### ISSUE TITLE
1.5.0 breaks Jest runs

### ISSUE THREAD

**Issue by mkucharz** [watson/ci-info#18]
**Details:**
 - Ci name: local environment 
 - Default env variables: none

**Additional context**

I've noticed it today so just after upgrading to 1.5.0, it looks `jest-resolve` has a problem with `vendors.json` - for some reason it cannot load it properly:

```
  ● Test suite failed to run

    Cannot find module './vendors' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.<anonymous> (node_modules/is-ci/node_modules/ci-info/index.js:3:15)
```

It might be more a `jest-resolve` problem, but it doesn't change the fact that all my builds (jest tests) are broken now.

**Comment by watson** [comment]
Sorry to hear that. it might be because jest-resolve doesn't support the same resolution algorithm as Node.js core. I'll try to update it to specify the full path (e.g. `./vendors.json` isntead of just `./vendors`) and release it as a patch. Hopefully that will fix it. If not, it would help if you could provide some example code that reproduces the problem 😃

**Comment by watson** [comment]
I've released v1.5.1 now. Please try it out and let me know if it fixes the problem.

**Comment by mkucharz** [comment]
@watson works great, thanks for fast reaction!
